import {test,expect, type Page} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const ctx=JSON.parse(process.env.E2E_DUPLICATE_CONTEXT??'{}');
const out=process.env.E2E_EVIDENCE_DIR!;
const front='gridfinity/base-front.stl',back='gridfinity/base-back.stl',bin='gridfinity/bin.stl';
const details=(page:Page)=>page.locator('summary',{hasText:'詳細設定'});
async function fit(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test('duplicate, add and replace keep quantity, drafts and conditions at narrow and desktop widths in both themes',async({page,request})=>{
  test.setTimeout(180_000);mkdirSync(out,{recursive:true});
  for(const width of [375,900])for(const colorScheme of ['dark','light'] as const){
    await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});
    await page.goto('/plates');await page.getByLabel('名前・モデル名で検索').fill(ctx.source.name);
    const row=page.locator('.plate-row').filter({hasText:ctx.source.name});await row.click({button:'right'});
    const dialog=page.getByRole('dialog');const duplicate=dialog.getByRole('button',{name:'複製',exact:true});
    expect(Math.abs((await duplicate.boundingBox())!.width-(await dialog.getByRole('button',{name:'編集',exact:true}).boundingBox())!.width)).toBeLessThan(1);
    await duplicate.click();const name=dialog.getByLabel('プレート名');await expect(name).toBeFocused();await expect(name).toHaveValue(ctx.source.name);
    await name.fill(`天馬ルームケース: base後 ${width} ${colorScheme}`);
    await fit(page);await page.screenshot({path:`${out}/duplicate-${width}-${colorScheme}.png`});
    await dialog.getByRole('button',{name:'複製',exact:true}).click();await expect(page).toHaveURL(/\/plates\/[a-f0-9-]{36}\?edit=1$/);
    const id=new URL(page.url()).pathname.split('/')[2],url='/api/plates/'+id;
    const copy=await (await request.get(url)).json();expect(copy.conditions).toEqual(ctx.source.conditions);expect(copy.models[0].id).not.toBe(ctx.source.models[0].id);expect(copy.version).toBe(1);
    const draftName=`別規格 ${width} ${colorScheme}`;await page.getByLabel('プレート名',{exact:true}).fill(draftName);
    for(const button of [page.getByRole('button',{name:'モデルを追加',exact:true}),page.getByRole('button',{name:front+'を差し替え'})])expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);
    await details(page).click();await page.getByLabel('壁の枚数（周）').fill('5');await page.getByLabel('充填率（%）').fill('25');
    await page.getByRole('combobox',{name:'インフィル',exact:true}).selectOption('adaptivecubic');
    await page.getByRole('combobox',{name:'ビルドプレート',exact:true}).selectOption('High Temp Plate');
    await page.getByLabel('ブリムを付ける').uncheck();
    await page.getByRole('button',{name:/^接触面のフィラメント:/}).click();
    await page.getByRole('dialog').locator(`button[data-filament-id="${ctx.second_material}"]`).click();
    const machine=await page.getByLabel('要求する機種・ノズル').inputValue(),process=await page.getByLabel('工程（品質）').inputValue();
    await page.getByRole('button',{name:front+'を差し替え',exact:true}).click();
    await expect(page.getByRole('searchbox',{name:'モデル名で検索'})).toBeFocused();
    await expect(page.getByRole('button',{name:front+' 選択済み',exact:true})).toBeDisabled();
    await page.getByRole('searchbox').fill('base-back');
    const option=page.getByRole('button',{name:back,exact:true});await option.focus();
    await expect(page.getByRole('tooltip').getByRole('status')).toHaveText('20.0 × 20.0 × 20.0 mm');
    await page.screenshot({path:`${out}/catalog-${width}-${colorScheme}.png`});
    await option.press('Enter');await expect(page.getByRole('button',{name:back+'を差し替え'})).toBeFocused();
    await expect(page.getByLabel(back+' の個数')).toHaveValue('10');await expect(page.getByLabel('プレート名',{exact:true})).toHaveValue(draftName);
    await expect(page.getByLabel('壁の枚数（周）')).toHaveValue('5');await expect(page.getByLabel('充填率（%）')).toHaveValue('25');
    await expect(page.getByRole('combobox',{name:'インフィル',exact:true})).toHaveValue('adaptivecubic');
    await expect(page.getByLabel('要求する機種・ノズル')).toHaveValue(machine);await expect(page.getByLabel('工程（品質）')).toHaveValue(process);
    await expect(page.getByRole('combobox',{name:'ビルドプレート',exact:true})).toHaveValue('High Temp Plate');await expect(page.getByLabel('ブリムを付ける')).not.toBeChecked();
    expect(await (await request.get(url)).json()).toEqual(copy);
    await page.getByRole('button',{name:'モデルを追加',exact:true}).click();
    await page.getByRole('searchbox').fill('bin');await page.getByRole('checkbox',{name:bin,exact:true}).check();
    await page.getByRole('searchbox').fill('base');await expect(page.getByRole('checkbox',{name:back,exact:true})).toBeDisabled();
    await page.getByRole('button',{name:'キャンセル',exact:true}).click();await expect(page.getByRole('button',{name:'モデルを追加',exact:true})).toBeFocused();
    await expect(page.getByLabel(bin+' の個数')).toHaveCount(0);
    await page.getByRole('button',{name:'モデルを追加',exact:true}).click();await page.getByRole('searchbox').fill('bin');await page.getByRole('checkbox',{name:bin,exact:true}).check();await page.getByRole('button',{name:'追加（1）',exact:true}).click();
    await expect(page.getByLabel(bin+' の個数')).toHaveValue('1');await expect(page.getByLabel(back+' の個数')).toHaveValue('10');
    await page.getByRole('button',{name:back+'を差し替え'}).click();await page.getByRole('searchbox').fill('');
    await expect(page.getByRole('button',{name:bin+' 選択済み',exact:true})).toBeDisabled();await page.getByRole('button',{name:'キャンセル',exact:true}).click();
    await fit(page);await page.getByLabel('プレート名',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`${out}/edited-${width}-${colorScheme}.png`,fullPage:true});
    await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page).toHaveURL(new RegExp('/plates/'+id+'$'));await page.reload();
    const saved=await (await request.get(url)).json();expect(saved.name).toBe(draftName);expect(saved.models.map((m:any)=>[m.source,m.quantity])).toEqual([[back,10],[bin,1]]);
    expect(saved.conditions).toEqual({...ctx.source.conditions,wall_loops:5,sparse_infill_density:25,sparse_infill_pattern:'adaptivecubic',bed_type:'High Temp Plate',brim_enabled:false,support_interface_filament_id:ctx.second_material});
    expect(await (await request.get('/api/plates/'+ctx.source.id)).json()).toEqual(ctx.source);
    // Cancelling the entire editor does not save even after temporary empty composition.
    await page.getByRole('button',{name:'構成を編集'}).click();
    for(const model of [back,bin])await page.getByRole('button',{name:model+'を構成から外す'}).click();
    await expect(page.getByRole('button',{name:'保存',exact:true})).toBeDisabled();
    await page.getByRole('button',{name:'モデルを追加',exact:true}).click();await page.getByRole('searchbox').fill('front');await page.getByRole('checkbox',{name:front,exact:true}).check();await page.getByRole('button',{name:'追加（1）',exact:true}).click();
    await page.getByRole('button',{name:'編集をやめる',exact:true}).click();expect(await (await request.get(url)).json()).toEqual(saved);
  }
});

test('real version conflict preserves edited composition, and 200 percent text remains operable',async({page,request})=>{
  const response=await request.post(`/api/plates/${ctx.source.id}/duplicate`,{data:{name:'Conflict copy'}});expect(response.status()).toBe(201);const copy=await response.json(),url='/api/plates/'+copy.id;
  await page.setViewportSize({width:375,height:812});await page.goto(`/plates/${copy.id}?edit=1`);
  await page.getByLabel('プレート名',{exact:true}).fill('未保存の変更');
  const rival=await request.put(url,{data:{...copy,name:'競合した名前',models:copy.models.map(({id,name,source,quantity}:any)=>({id,name,source,quantity})),imported:undefined,id:undefined}});expect(rival.status()).toBe(200);
  await page.getByRole('button',{name:front+'を差し替え'}).click();await page.getByRole('button',{name:back,exact:true}).click();
  await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'更新'})).toBeVisible();await expect(page.getByLabel('プレート名',{exact:true})).toHaveValue('未保存の変更');await expect(page.getByLabel(back+' の個数')).toHaveValue('10');
  const before=await page.getByLabel('プレート名',{exact:true}).evaluate(e=>parseFloat(getComputedStyle(e).fontSize));
  await page.addStyleTag({content:':root {--fs-xs:24px;--fs-sm:28px;--fs-md:30px;--fs-lg:32px;--fs-xl:34px}'});
  expect(await page.getByLabel('プレート名',{exact:true}).evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBe(before*2);
  await fit(page);await page.getByRole('button',{name:'モデルを追加',exact:true}).click();await fit(page);await page.getByRole('button',{name:'キャンセル',exact:true}).click();
  await page.screenshot({path:`${out}/conflict-text200.png`,fullPage:true});
});
