import {selectMaterial} from './plate-material';
import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const ctx=JSON.parse(process.env.E2E_PLATE_CONTEXT ?? '{}');
test('plates name no machine, process or bed and enqueue on any printer at desktop and narrow widths',async({page,request})=>{
  test.setTimeout(90_000);page.setDefaultTimeout(10_000);
  mkdirSync(process.env.E2E_EVIDENCE_DIR!,{recursive:true});
  for(const [width,colorScheme] of [[320,'dark'],[900,'light']] as const){
    await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme});
    await page.goto('/plates/new');
    const before=(await (await request.get('/api/plates')).json());
    await page.locator('[data-stl-preview]').hover();
    await expect(page.getByRole('tooltip').getByRole('status')).toHaveText('20.0 × 20.0 × 20.0 mm');
    expect(await (await request.get('/api/plates')).json()).toEqual(before);
    await page.screenshot({path:`${process.env.E2E_EVIDENCE_DIR}/hover-live-${width}-${colorScheme}.png`});
    await page.mouse.move(0,0);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'構成を確認（1）'}).click();
    await page.getByLabel('プレート名',{exact:true}).fill(`Gridfinity ${width===320?'前':'後'}`);
    await page.getByLabel('parts/cube.stl の個数').fill('2');
    for(const name of ['要求する機種・ノズル','工程（品質）','ビルドプレート'])await expect(page.getByLabel(name,{exact:true})).toHaveCount(0);
    await selectMaterial(page,ctx.filament);
    await page.getByRole('button',{name:'保存',exact:true}).click();
    await expect(page).toHaveURL(/\/plates\/[0-9a-f-]{36}$/);
    await expect(page.getByRole('complementary',{name:'STLプレビュー'}).getByRole('status')).toHaveText('20.0 × 20.0 × 20.0 mm');
    const path=new URL(page.url()).pathname;
    await expect(page.getByLabel('追加先のプリンター').locator('option')).toHaveCount(4);
    await page.getByLabel('追加先のプリンター').selectOption(ctx.devices[1]);await page.reload();
    await expect(page.getByLabel('追加先のプリンター')).toHaveValue(ctx.devices[1]);
    const queue=async()=> (await request.get(`/api/queue?printer_id=${ctx.devices[1]}`)).json();
    const count=(await queue()).waiting.length;
    const add=page.getByRole('button',{name:'印刷キューへ',exact:true});await expect(add).toBeEnabled();
    await add.evaluate((button:HTMLButtonElement)=>{button.click();button.click();});
    await expect(page.getByRole('status').filter({hasText:'キューに追加しました'})).toBeVisible();expect((await queue()).waiting.length).toBe(count+1);
    await expect(page).toHaveURL(new RegExp(path+'$'));await page.reload();await add.click();
    await expect(page.getByRole('status').filter({hasText:'キューに追加しました'})).toBeVisible();expect((await queue()).waiting.length).toBe(count+2);
    expect((await queue()).current).toBeNull();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:`${process.env.E2E_EVIDENCE_DIR}/plate-${width}-${colorScheme}.png`,fullPage:true});
    await page.getByRole('button',{name:'構成を編集'}).click();
    await selectMaterial(page,null);
    await page.getByRole('button',{name:'保存',exact:true}).click();
    await expect(add).toBeDisabled();
    const waiting=(await queue()).waiting.filter((job:any)=>`/plates/${job.plate_id}`===path);
    expect(waiting).toHaveLength(2);expect(waiting.every((job:any)=>job.filament_id===null && job.hold_reason)).toBe(true);
    await page.getByRole('button',{name:'構成を編集'}).click();
    await selectMaterial(page,ctx.filament);await page.getByRole('button',{name:'保存',exact:true}).click();
    await expect(add).toBeEnabled();
    await page.addStyleTag({content:'html {font-size:200% !important}'});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  }
});
